In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
sns.set_theme (style="whitegrid",palette="muted")
RANDOM_STATE = 42

In [ ]:
# Load the dataset
df_raw = pd.read_csv('/content/Z-Alizadeh sani dataset (2).csv')

# Assuming the last column is the target variable based on the problem description
X_raw = df_raw.iloc[:,:-1].copy()
y_raw = df_raw.iloc[:,-1].copy()

print("Feature matrix shape: ", X_raw.shape)
print("Target shape:", y_raw.shape)
display(X_raw.head())
display(y_raw.head())

Feature matrix shape:  (303, 54)
Target shape: (303,)

   Age  Weight  Length    Sex  ...  PLT  EF-TTE  Region RWMA     VHD
0   53      90     175   Male  ...  261      50            0       N
1   67      70     157  Fmale  ...  165      40            4       N
2   54      54     164   Male  ...  230      40            2    mild
3   66      67     158  Fmale  ...  742      55            0  Severe
4   50      87     153  Fmale  ...  274      50            0  Severe

[5 rows x 54 columns]

0       Cad
1       Cad
2       Cad
3    Normal
4    Normal
Name: Cath, dtype: object

In [ ]:
# Preprocessing: Feature Analysis, Encoding, and Scaling
print("### 1. Full Feature-Level Analysis (from X_raw)")

feature_data = []
for col in X_raw.columns:
  unique_values_for_type_detection = X_raw[col].unique()
  num_unique = len(unique_values_for_type_detection)

  # Revised logic for detected_type to explicitly handle single-unique-value object columns
  if 2 <= num_unique <= 5:
    detected_type = 'Categorical'
  elif num_unique == 1:
    if X_raw[col].dtype == 'object':
      detected_type = 'Categorical' # Treat single unique object values as categorical
    else:
      detected_type = 'Numerical' # Treat single unique non-object values as numerical (constant)
  else: # num_unique > 5
    detected_type = 'Numerical'

  # Collect full unique values for display and missing values (this part should always run)
  unique_values_list = X_raw[col].unique().tolist()
  missing_values = X_raw[col].isnull().sum()

  # Limit unique values display to avoid clutter
  unique_val_display = str(unique_values_list) if len(unique_values_list) <= 10 else f'{len(unique_values_list)} unique values'

  feature_data.append({
      'Feature': col,
      'Pandas dtype': str(X_raw[col].dtype),
      '# Unique Values': num_unique,
      'Unique Values': unique_val_display,
      'Missing Values': missing_values,
      'Detected Type': detected_type
  })

feature_analysis_df = pd.DataFrame(feature_data)
display(feature_analysis_df)
print("\n### 2. Low-Cardinality Features (2-10 Unique Values)")
low_cardinality_features = feature_analysis_df[
    (feature_analysis_df['# Unique Values'] >= 2) &
    (feature_analysis_df['# Unique Values'] <= 10)
]
display(low_cardinality_features[['Feature','# Unique Values', 'Unique Values', 'Pandas dtype', 'Detected Type' ]])
print("\nFeatures detected as Categorical (2-5 unique values or 1 unique object value):",
      feature_analysis_df[feature_analysis_df['Detected Type'] == 'Categorical']['Feature'].tolist())
print("\nFeatures detected as Numerical (6+ unique values or 1 unique non-object value):",
      feature_analysis_df[feature_analysis_df['Detected Type'] == 'Numerical']['Feature'].tolist())

### 1. Full Feature-Level Analysis (from X_raw)

                  Feature Pandas dtype  ...  Missing Values Detected Type
0                     Age        int64  ...               0     Numerical
1                  Weight        int64  ...               0     Numerical
2                  Length        int64  ...               0     Numerical
3                     Sex       object  ...               0   Categorical
4                     BMI      float64  ...               0     Numerical
5                      DM        int64  ...               0   Categorical
6                     HTN        int64  ...               0   Categorical
7          Current Smoker        int64  ...               0   Categorical
8               EX-Smoker        int64  ...               0   Categorical
9                      FH        int64  ...               0   Categorical
10                Obesity       object  ...               0   Categorical
11                    CRF       object  ...               0   Categorical
12                    CVA       object  ...               0   Categorical
13         Airway disease       object  ...               0   Categorical
14        Thyroid Disease       object  ...               0   Categorical
15                    CHF       object  ...               0   Categorical
16                    DLP       object  ...               0   Categorical
17                     BP        int64  ...               0     Numerical
18                     PR        int64  ...               0     Numerical
19                  Edema        int64  ...               0   Categorical
20  Weak Peripheral Pulse       object  ...               0   Categorical
21             Lung rales       object  ...               0   Categorical
22        Systolic Murmur       object  ...               0   Categorical
23       Diastolic Murmur       object  ...               0   Categorical
24     Typical Chest Pain        int64  ...               0   Categorical
25                Dyspnea       object  ...               0   Categorical
26         Function Class        int64  ...               0   Categorical
27               Atypical       object  ...               0   Categorical
28             Nonanginal       object  ...               0   Categorical
29          Exertional CP       object  ...               0   Categorical
30              LowTH Ang       object  ...               0   Categorical
31                 Q Wave        int64  ...               0   Categorical
32           St Elevation        int64  ...               0   Categorical
33          St Depression        int64  ...               0   Categorical
34             Tinversion        int64  ...               0   Categorical
35                    LVH       object  ...               0   Categorical
36     Poor R Progression       object  ...               0   Categorical
37                    FBS        int64  ...               0     Numerical
38                     CR      float64  ...               0     Numerical
39                     TG        int64  ...               0     Numerical
40                    LDL        int64  ...               0     Numerical
41                    HDL      float64  ...               0     Numerical
42                    BUN        int64  ...               0     Numerical
43                    ESR        int64  ...               0     Numerical
44                     HB      float64  ...               0     Numerical
45                      K      float64  ...               0     Numerical
46                     Na        int64  ...               0     Numerical
47                    WBC        int64  ...               0     Numerical
48                  Lymph        int64  ...               0     Numerical
49                   Neut        int64  ...               0     Numerical
50                    PLT        int64  ...               0     Numerical
51                 EF-TTE        int64  ...               0     Numerical
52            Region RWMA        int64  ...               0   Categorical
53                    VHD       object  ...               0   Categorical

[54 rows x 6 columns]

### 2. Low-Cardinality Features (2-10 Unique Values)

                  Feature  # Unique Values  ... Pandas dtype Detected Type
3                     Sex                2  ...       object   Categorical
5                      DM                2  ...        int64   Categorical
6                     HTN                2  ...        int64   Categorical
7          Current Smoker                2  ...        int64   Categorical
8               EX-Smoker                2  ...        int64   Categorical
9                      FH                2  ...        int64   Categorical
10                Obesity                2  ...       object   Categorical
11                    CRF                2  ...       object   Categorical
12                    CVA                2  ...       object   Categorical
13         Airway disease                2  ...       object   Categorical
14        Thyroid Disease                2  ...       object   Categorical
15                    CHF                2  ...       object   Categorical
16                    DLP                2  ...       object   Categorical
19                  Edema                2  ...        int64   Categorical
20  Weak Peripheral Pulse                2  ...       object   Categorical
21             Lung rales                2  ...       object   Categorical
22        Systolic Murmur                2  ...       object   Categorical
23       Diastolic Murmur                2  ...       object   Categorical
24     Typical Chest Pain                2  ...        int64   Categorical
25                Dyspnea                2  ...       object   Categorical
26         Function Class                4  ...        int64   Categorical
27               Atypical                2  ...       object   Categorical
28             Nonanginal                2  ...       object   Categorical
30              LowTH Ang                2  ...       object   Categorical
31                 Q Wave                2  ...        int64   Categorical
32           St Elevation                2  ...        int64   Categorical
33          St Depression                2  ...        int64   Categorical
34             Tinversion                2  ...        int64   Categorical
35                    LVH                2  ...       object   Categorical
36     Poor R Progression                2  ...       object   Categorical
52            Region RWMA                5  ...        int64   Categorical
53                    VHD                4  ...       object   Categorical

[32 rows x 5 columns]

Features detected as Categorical (2-5 unique values or 1 unique object value): ['Sex', 'DM', 'HTN', 'Current Smoker', 'EX-Smoker', 'FH', 'Obesity', 'CRF', 'CVA', 'Airway disease', 'Thyroid Disease', 'CHF', 'DLP', 'Edema', 'Weak Peripheral Pulse', 'Lung rales', 'Systolic Murmur', 'Diastolic Murmur', 'Typical Chest Pain', 'Dyspnea', 'Function Class', 'Atypical', 'Nonanginal', 'Exertional CP', 'LowTH Ang', 'Q Wave', 'St Elevation', 'St Depression', 'Tinversion', 'LVH', 'Poor R Progression', 'Region RWMA', 'VHD']

Features detected as Numerical (6+ unique values or 1 unique non-object value): ['Age', 'Weight', 'Length', 'BMI', 'BP', 'PR', 'FBS', 'CR', 'TG', 'LDL', 'HDL', 'BUN', 'ESR', 'HB', 'K', 'Na', 'WBC', 'Lymph', 'Neut', 'PLT', 'EF-TTE']

In [ ]:
print("### 3. Applying Label Encoding and Preparing Data for Scaling")
from sklearn.preprocessing import LabelEncoder

X_preprocessed = X_raw.copy()
label_encoders = {} # Store encoders and their mappings
feature_label_encoded = []

# Apply Label Encoding based on rules
for idx, row in feature_analysis_df.iterrows():
  col = row['Feature']
  if row['Detected Type'] == 'Categorical' and row ['Pandas dtype'] == 'object':
    le = LabelEncoder()
    X_preprocessed[col] = le.fit_transform(X_preprocessed[col])
    label_encoders[col] = {
        'encoder' : le,
        'mapping' : dict(zip(le.classes_, le.transform(le.classes_)))
    }
    feature_label_encoded.append(col)
    print(f" - Label Encoded feature '{col}' (object dtype, categorical). Mapping: {label_encoders[col]['mapping']}")

  # Identify columns for scaling (numerical features as detected by unique value count)
  numerical_col_for_scaling = feature_analysis_df[feature_analysis_df['Detected Type'] == 'Numerical']['Feature'].tolist()

  # Identify categorical columns that are NOT scaled (these are either non-object dtype or were label encoded)
# This includes features detected as categorical and non-object dtype which should be kept as is.
categorical_cols_not_scaled = [col for col in X_preprocessed.columns if col not in numerical_col_for_scaling]

print(f"\nFeatures identified for scaling (Numerical): {numerical_col_for_scaling}")
print(f"\nFeatures identified as categorical (either Label Encoded or kept as is): {categorical_cols_not_scaled}")

print("\nFirst 5 rows of X_processed after Label Encoding:")
display(X_preprocessed.head())

### 3. Applying Label Encoding and Preparing Data for Scaling
 - Label Encoded feature 'Sex' (object dtype, categorical). Mapping: {'Fmale': np.int64(0), 'Male': np.int64(1)}
 - Label Encoded feature 'Obesity' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'CRF' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'CVA' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Airway disease' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Thyroid Disease' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'CHF' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'DLP' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Weak Peripheral Pulse' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Lung rales' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Systolic Murmur' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Diastolic Murmur' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Dyspnea' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Atypical' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Nonanginal' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Exertional CP' (object dtype, categorical). Mapping: {'N': np.int64(0)}
 - Label Encoded feature 'LowTH Ang' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'LVH' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'Poor R Progression' (object dtype, categorical). Mapping: {'N': np.int64(0), 'Y': np.int64(1)}
 - Label Encoded feature 'VHD' (object dtype, categorical). Mapping: {'Moderate': np.int64(0), 'N': np.int64(1), 'Severe': np.int64(2), 'mild': np.int64(3)}

Features identified for scaling (Numerical): ['Age', 'Weight', 'Length', 'BMI', 'BP', 'PR', 'FBS', 'CR', 'TG', 'LDL', 'HDL', 'BUN', 'ESR', 'HB', 'K', 'Na', 'WBC', 'Lymph', 'Neut', 'PLT', 'EF-TTE']

Features identified as categorical (either Label Encoded or kept as is): ['Sex', 'DM', 'HTN', 'Current Smoker', 'EX-Smoker', 'FH', 'Obesity', 'CRF', 'CVA', 'Airway disease', 'Thyroid Disease', 'CHF', 'DLP', 'Edema', 'Weak Peripheral Pulse', 'Lung rales', 'Systolic Murmur', 'Diastolic Murmur', 'Typical Chest Pain', 'Dyspnea', 'Function Class', 'Atypical', 'Nonanginal', 'Exertional CP', 'LowTH Ang', 'Q Wave', 'St Elevation', 'St Depression', 'Tinversion', 'LVH', 'Poor R Progression', 'Region RWMA', 'VHD']

First 5 rows of X_processed after Label Encoding:

   Age  Weight  Length  Sex        BMI  ...  Neut  PLT  EF-TTE  Region RWMA  VHD
0   53      90     175    1  29.387755  ...    52  261      50            0    1
1   67      70     157    0  28.398718  ...    55  165      40            4    1
2   54      54     164    1  20.077335  ...    60  230      40            2    3
3   66      67     158    0  26.838648  ...    72  742      55            0    2
4   50      87     153    0  37.165193  ...    39  274      50            0    2

[5 rows x 54 columns]

In [ ]:
# Encode the target
target_column =  y_raw.name # Corrected from y_raw.columns[0]
print("Target column:", target_column)
print("Unique labels:",y_raw.unique()) # Operate directly on y_raw

y =(y_raw.astype(str).str.strip().str.lower().map({"normal":0, "cad":1})) # Operate directly on y_raw

if y.isna().any():
  raise ValueError("Unexpected target labels. Inspect the unique values above.")

display(y.value_counts().rename(index={0:"normal",1:"CAD"})) # Corrected indentation

Target column: Cath
Unique labels: ['Cad' 'Normal']

Cath
CAD       216
normal     87
Name: count, dtype: int64

In [ ]:
# Train/Test Split
X_train, x_test, y_train, y_test = train_test_split(
 X_preprocessed, y,
   test_size=0.2, random_state= RANDOM_STATE,
   stratify=y
 )

print("Traning shape:",X_train.shape)
print("Testing shape:",x_test.shape)

Traning shape: (242, 54)
Testing shape: (61, 54)

In [ ]:
numerical_col_for_scaling

['Age',
 'Weight',
 'Length',
 'BMI',
 'BP',
 'PR',
 'FBS',
 'CR',
 'TG',
 'LDL',
 'HDL',
 'BUN',
 'ESR',
 'HB',
 'K',
 'Na',
 'WBC',
 'Lymph',
 'Neut',
 'PLT',
 'EF-TTE']

In [ ]:
scalar = StandardScaler()

# Separate numerical and categorical columns for training data
X_train_num = X_train[numerical_col_for_scaling]
X_train_cat = X_train[categorical_cols_not_scaled]

# Separate numerical and categorical columns for testing data
X_test_num = x_test[numerical_col_for_scaling]
X_test_cat = x_test[categorical_cols_not_scaled] # Corrected: should use categorical_cols_not_scaled

# Fit and transform the scaler only on numerical training data
X_train_scaled_num = scalar.fit_transform(X_train_num) # Corrected: fit_transform
# Transform the testing data using the scaler fitted on training data
X_test_scaled_num = scalar.transform(X_test_num) # Corrected: transform

# Convert scaled numerical arrays back to DataFrame for concatenation
X_train_scaled_num_df = pd.DataFrame(X_train_scaled_num, columns=numerical_col_for_scaling, index = X_train.index) # Corrected syntax and index
X_test_scaled_num_df = pd.DataFrame(X_test_scaled_num, columns=numerical_col_for_scaling, index = x_test.index) # Corrected syntax and index

# Reconstruct the full scaled dataframes by concatenating scaled numerical with unscaled categorical features
X_train_scaled = pd.concat([X_train_scaled_num_df,X_train_cat],axis=1)
X_test_scaled = pd.concat([X_test_scaled_num_df,X_test_cat],axis=1)

# Ensure column order is consistent (optional but good practice)
X_train_scaled = X_train_scaled[X_train.columns]
X_test_scaled = X_test_scaled[x_test.columns]

print("Scaled training shape:", X_train_scaled.shape)
print("First five feature means (from numerical scaled features):")
print(X_train_scaled_num[:, :5].mean(axis=0))
print("First five feature stds (from numerical scaled features):")
print(X_train_scaled_num[:, :5].std(axis=0))

print("\nFirst 5 rows of X_train_scaled (showing a mix of scaled numerical and original categorical values):")
display(X_train_scaled.head())

Scaled training shape: (242, 54)
First five feature means (from numerical scaled features):
[-1.90848255e-16  2.56911113e-17 -8.07434927e-17 -7.41372069e-16
  3.18386272e-16]
First five feature stds (from numerical scaled features):
[1. 1. 1. 1. 1.]

First 5 rows of X_train_scaled (showing a mix of scaled numerical and original categorical values):

          Age    Weight    Length  Sex  ...       PLT    EF-TTE  Region RWMA  VHD
149  1.209246 -1.176117 -0.866040    0  ...  0.586853  0.865624            0    1
25   0.626496 -0.043461 -0.097537    1  ... -0.489897 -0.240400            3    3
34  -0.344754  0.441963  0.231821    1  ... -0.200621 -3.005462            4    0
176 -1.024628  1.008292  0.451394    1  ... -0.136337 -0.240400            0    3
182  1.694871  0.846484  1.549255    1  ... -0.843456  0.312612            0    3

[5 rows x 54 columns]